# ---------------------------------------------------------------------------------------------------------------------
# Resource group label variables - used in terraform-null-label
# ---------------------------------------------------------------------------------------------------------------------
variable "label_namespace" {
  description = "Namespace, which could be your organization name. First item in naming sequence."
  default     = ""
  type        = string
}

variable "label_stage" {
  description = "Stage, e.g. `prod`, `staging`, `dev`, or `test`. Second item in naming sequence."
  default     = ""
  type        = string
}

variable "label_name" {
  description = "Name, which could be the name of your solution or app. Third item in naming sequence."
  default     = ""
  type        = string
}

variable "label_attributes" {
  type        = list(string)
  default     = []
  description = "Additional attributes, e.g. `1`"
}

# ---------------------------------------------------------------------------------------------------------------------
# Variables that you might want to change
# ---------------------------------------------------------------------------------------------------------------------
variable "client_machine_pip" {
  type        = string
  description = "Your workstation machine public ip"
  default     = ""
}

variable "environment" {
  type        = string
  description = "This variable defines the environment tag"
  default     = "staging"
}

variable "location" {
  type        = string
  description = "(Required) Azure region where resources will be created"
  default     = "North Europe"
}

variable "purge_protection" {
  description = "Defines if Purge Protection is enabled for this Key Vault"
  type        = bool
  default     = true
}

variable "default_tags" {
  description = "Default billing tags to be applied across all resources"
  type        = map(string)
  default     = {}
}

# ---------------------------------------------------------------------------------------------------------------------
# Resource variables set by terraform-null-label
# ---------------------------------------------------------------------------------------------------------------------
variable "resource_group_name" {
  default     = ""
  type        = string
  description = "The resource group name. If not provided, the resource group will be generated by the label module in the format namespace-stage-name. Must be 1-90 characters long. Alphanumerics, underscores, parentheses, hyphens, periods."
}

variable "storage_account_name" {
  type        = string
  default     = ""
  description = "Storage account name. If not provided, the name will be generated by the label module in the format namespace-stage-name. Must be 3-24	characters, with lowercase letters and numbers only."
}

variable "storage_container_name" {
  type        = string
  default     = ""
  description = "Storage container name. If not provided, the name will be generated by the label module in the format namespace-stage-name. Must be 3-24	characters, with lowercase letters and numbers only."
}

variable "key_vault_name" {
  type        = string
  default     = ""
  description = "Key vault name. If not provided, the name will be generated by the label module in the format namespace-stage-name. Must be 1-127 character string, starting with a letter and containing only 0-9, a-z, A-Z, and -"
}

# ---------------------------------------------------------------------------------------------------------------------
# Some default variables using simplest settings on the Azure Storage Account
# ---------------------------------------------------------------------------------------------------------------------
variable "storage_account_tier" {
  type        = string
  default     = "Standard"
  description = "Defines the Tier to use for this storage account. Valid options are Standard and Premium"
}

variable "storage_account_replication_type" {
  type        = string
  default     = "LRS"
  description = "Defines the type of replication to use for this storage account. Valid options are LRS, GRS, RAGRS, ZRS, GZRS and RAGZRS."
}

variable "key_vault_key_type" {
  type        = string
  default     = "RSA"
  description = "Specifies the Key Type to use for this Key Vault Key. For Terraform state, supply RSA or RSA-HSM."
}

variable "key_vault_sku_name" {
  type        = string
  default     = "standard"
  description = "The Name of the SKU used for this Key Vault. Possible values are standard and premium."
}

# ---------------------------------------------------------------------------------------------------------------------
# kv- - KeyVault permissions
# ---------------------------------------------------------------------------------------------------------------------
variable "kv-key-permissions-full" {
  type        = list(string)
  description = "List of full key permissions, must be one or more from the following: Backup, Create, Decrypt, Delete, Encrypt, Get, Import, List, Purge, Recover, Restore, Sign, UnwrapKey, Update, Verify, WrapKey, Release, Rotate, GetRotationPolicy, and SetRotationPolicy."
  default     = ["Backup", "Create", "Decrypt", "Delete", "Encrypt", "Get", "Import", "List", "Purge", "Recover", "Restore", "Sign", "UnwrapKey", "Update", "Verify", "WrapKey", "Release", "Rotate", "GetRotationPolicy", "SetRotationPolicy"]
}

variable "kv-secret-permissions-full" {
  type        = list(string)
  description = "List of full secret permissions, must be one or more from the following: Backup, Delete, Get, List, Purge, Recover, Restore and Set."
  default     = ["Backup", "Delete", "Get", "List", "Purge", "Recover", "Restore", "Set"]
}

variable "kv-certificate-permissions-full" {
  type        = list(string)
  description = "List of full certificate permissions, must be one or more from the following: Backup, Create, Delete, DeleteIssuers, Get, GetIssuers, Import, List, ListIssuers, ManageContacts, ManageIssuers, Purge, Recover, Restore, SetIssuers and Update"
  default     = ["Backup", "Create", "Delete", "DeleteIssuers", "Get", "GetIssuers", "Import", "List", "ListIssuers", "ManageContacts", "ManageIssuers", "Purge", "Recover", "Restore", "SetIssuers", "Update"]
}

variable "kv-storage-permissions-full" {
  type        = list(string)
  description = "List of full storage permissions, must be one or more from the following: Backup, Delete, DeleteSAS, Get, GetSAS, List, ListSAS, Purge, Recover, RegenerateKey, Restore, Set, SetSAS and Update."
  default     = ["Backup", "Delete", "DeleteSAS", "Get", "GetSAS", "List", "ListSAS", "Purge", "Recover", "RegenerateKey", "Restore", "Set", "SetSAS", "Update"]
}